Music:
  - Name: "RamenTwig/AstralAlley"
    Weight: 2
  - Name: "RamenTwig/CorridorsofTime"
    Weight: 1.5
  - Name: "RamenTwig/FirefliesOnThePorch"
    Weight: 2
  - Name: "RamenTwig/SecretofTheForest"
    Weight: 3
  - Name: "RamenTwig/StickerbrushSymphony"
    Weight: 3
  - Name: "The-Hole-at-the-Center-of-Everything_1"