ASide:
 - Room: "C-01"
   Holes:
   - Side: Down
     Idx: 0
     Kind: none
   - Side: Down
     Idx: 1
     Kind: none
   - Side: Up
     Idx: 0
     Kind: none
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: inout
   InternalEdges:
     - Split: LeftToRight
       ReqOut:
         Dashes: one
       ReqIn: 
         Dashes: two
 - Room: "C-02"
   Holes:
   - Side: Left
     Idx: 0 
     Kind: inout
   - Side: Down
     Idx: 0
     Kind: none
   - Side: Down
     Idx: 1
     Kind: none
   - Side: Down
     Idx: 2
     Kind: none
   - Side: Down 
     Idx: 3
     Kind: none
   - Side: Down
     Idx: 4
     Kind: inout
   - Side: Down 
     Idx: 5
     Kind: none
   - Side: Down 
     Idx: 6
     Kind: none
   - Side: Down 
     Idx: 7
     Kind: none
   - Side: Down
     Idx: 8
     Kind: none
   - Side: Right
     Idx: 0
     Kind: inout
   InternalEdges:
     - Split: LeftToRight
       ReqOut:
         - Dashes: one
           Difficulty: hard
       ReqIn:
         Or:
         - Dashes: one
           Difficulty: hard
           Key: true
           KeyholeID: 196
         - Dashes: two
           Key: true
           KeyholeID: 196
 - Room: "C-03"
   Holes:
   - Side: Up
     Idx: 0 
     Kind: inout
   InternalEdges:
     - To: "bottom"
       ReqOut:
         Dashes: one
   Subrooms:
     - Room: "bottom"
     - Collectable: 0
       ReqBoth:
           Or:
           - Dashes: one
             Difficulty: hard
           - Dashes: two
 - Room: "C-04"
   Holes:
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: out
   - Side: Down
     Idx: 0
     Kind: none
   - Side: Down
     Idx: 1
     Kind: none
   - Side: Down
     Idx: 2
     Kind: none
   - Side: Down
     Idx: 3
     Kind: none
   - Side: Down
     Idx: 4
     Kind: none
   - Side: Down
     Idx: 5
     Kind: none
   - Side: Down
     Idx: 6
     Kind: none
   - Side: Down
     Idx: 7
     Kind: none
     ReqBoth:
         Or:
         - Dashes: one
           Difficulty: hard
         - Dashes: two
 - Room: "C-05"
   Holes:
   - Side: Down
     Idx: 0
     Kind: none
   - Side: Down
     Idx: 1
     Kind: none
   - Side: Down
     Idx: 2
     Kind: none
   - Side: Down
     Idx: 3
     Kind: none
   - Side: Down
     Idx: 4
     Kind: none
   - Side: Down
     Idx: 5
     Kind: none
   - Side: Left
     Idx: 0
     Kind: inout
     ReqOut: 
       Dashes: one
       Difficulty: perfect
   - Side: Left
     Idx: 1
     Kind: inout
   - Side: Up
     Idx: 0
     Kind: inout
     ReqOut:
       Dashes: two
   - Side: Right
     Idx: 0
     Kind: inout
 - Room: "C-06"
   Holes:
   - Side: Down 
     Idx: 0
     Kind: none
   - Side: Down 
     Idx: 1
     Kind: none
   - Side: Down 
     Idx: 2
     Kind: none
   - Side: Down 
     Idx: 3
     Kind: none
   - Side: Down 
     Idx: 4
     Kind: none
   - Side: Down 
     Idx: 5
     Kind: none
   - Side: Down 
     Idx: 6
     Kind: none
   - Side: Down 
     Idx: 7
     Kind: none
   - Side: Up
     Idx: 0
     Kind: none
   - Side: Up
     Idx: 1
     Kind: none
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: inout
   InternalEdges:
     - Split: LeftToRight
       ReqOut:
         Or:
         - Dashes: one
           Difficulty: hard
         - Dashes: two
       ReqIn:
         Dashes: two
         Difficulty: perfect
 - Room: "C-Cassette"
   End: true
   Holes:
   - Side: Left
     Idx: 0
     Kind: in
     ReqBoth:
         Or:
         - Dashes: one
           Difficulty: hard
         - Dashes: two