ASide:
 - Room: "C-01"
   Holes:
   - Side: Up
     Idx: 0
     Kind: unknown
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Down
     Idx: 0
     Kind: unknown
     ReqIn: 
       Dashes: one
   InternalEdges:
     - To: "right"
       ReqOut:
         Dashes: one
       ReqIn: 
         Dashes: two
   Subrooms:
   - Room: "right"
     Holes:
     - Side: Down
       Idx: 1
       Kind: unknown
     - Side: Right
       Idx: 0
       Kind: inout
 - Room: "C-02" # use empty space tag for the falling blocks in the room
   Holes:
   - Side: Left
     Idx: 0
     Kind: inout
     ReqIn:
        Or:
        - Dashes: two
        - Dashes: one
          Difficulty: hard
   - Side: Down
     Idx: 0
     Kind: unknown
   - Side: Down
     Idx: 1
     Kind: unknown
   - Side: Down
     Idx: 2
     Kind: unknown
   - Side: Down 
     Idx: 3
     Kind: unknown
   - Side: Down
     Idx: 4
     Kind: inout
   InternalEdges:
     - To: "right"
   ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
          Key: true
          KeyholeID: 196
        - Dashes: two
          Key: true
          KeyholeID: 196
   Subrooms:
   - Room: "right"
     Holes: 
     - Side: Down 
       Idx: 5
       Kind: unknown
     - Side: Down 
       Idx: 6
       Kind: unknown
     - Side: Down 
       Idx: 7
       Kind: unknown
     - Side: Down
       Idx: 8
       Kind: unknown
     - Side: Right
       Idx: 0
       Kind: inout
       ReqBoth:
          Or:
          - Dashes: one
            Difficulty: hard
            Key: true
            KeyholeID: 196
          - Dashes: two
            Key: true
            KeyholeID: 196
 - Room: "C-03"
   Holes:
   - Side: Up
     Idx: 0 
     Kind: inout
     ReqBoth:
         Or:
         - Dashes: one
           Difficulty: hard
         - Dashes: two
   InternalEdges:
     - Collectable: 0
   ReqOut:
         Or:
         - Dashes: one
           Difficulty: hard
         - Dashes: two
 - Room: "C-04"
   Holes:
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: out
     ReqOut:
       Or:
       - Dashes: one
         Difficulty: master
       - Dashes: two
         Difficulty: expert
   - Side: Down
     Idx: 0
     Kind: unknown
   - Side: Down
     Idx: 1
     Kind: unknown
   - Side: Down
     Idx: 2
     Kind: unknown
   - Side: Down
     Idx: 3
     Kind: unknown
   - Side: Down
     Idx: 4
     Kind: unknown
   - Side: Down
     Idx: 5
     Kind: unknown
   - Side: Down
     Idx: 6
     Kind: unknown
   - Side: Down
     Idx: 7
     Kind: unknown
 - Room: "C-05"
   Holes:
   - Side: Down
     Idx: 3
     Kind: unknown
   - Side: Down
     Idx: 4
     Kind: unknown
   - Side: Down
     Idx: 5
     Kind: unknown
   - Side: Right
     Idx: 0
     Kind: inout
     ReqBoth:
       Or:
       - Dashes: one
       - Dashes: two
   InternalEdges:
   - To: "right"
     ReqBoth:
         Dashes: one
   Subrooms:
   - Room: "right"
     Holes:
     - Side: Down
       Idx: 0
       Kind: unknown
     - Side: Down
       Idx: 1
       Kind: unknown
     - Side: Down
       Idx: 2
       Kind: unknown
       ReqIn:
         Dashes: two
     - Side: Left
       Idx: 0
       Kind: unknown
       ReqOut:
         Or:
         - Dashes: one
           Difficulty: expert
         - Dashes: two
           Difficulty: hard
     - Side: Left
       Idx: 1
       Kind: inout
       ReqOut: 
         Dashes: one
     - Side: Up
       Idx: 0
       Kind: unknown
       ReqOut:
         Dashes: two
 - Room: "C-06"
   Holes:
   - Side: Down 
     Idx: 5
     Kind: unknown
   - Side: Down 
     Idx: 6
     Kind: unknown
   - Side: Down 
     Idx: 7
     Kind: unknown
   - Side: Right
     Idx: 0
     Kind: inout
   InternalEdges:
     - To: "right"
       ReqOut:
         Or:
         - Dashes: one
           Difficulty: hard
         - Dashes: two
       ReqIn:
         Or:
         - Dashes: two
           Difficulty: master
         - Dashes: one
           Difficulty: perfect
   Subrooms:
   - Room: "right"
     Holes:
     - Side: Left
       Idx: 0
       Kind: inout
     - Side: Up
       Idx: 0
       Kind: unknown
     - Side: Up
       Idx: 1
       Kind: unknown
     - Side: Down 
       Idx: 0
       Kind: unknown
     - Side: Down 
       Idx: 1
       Kind: unknown
     - Side: Down 
       Idx: 2
       Kind: unknown
     - Side: Down 
       Idx: 3
       Kind: unknown
     - Side: Down 
       Idx: 4
       Kind: unknown
   Tweaks:
   - Name: "spinner"
     ID: 1074
     Update: 
       Remove: true
   - Name: "spinner"
     ID: 1033
     Update: 
       Remove: true
 - Room: "C-Cassette"
   End: true
   Holes:
   - Side: Left
     Idx: 0
     Kind: in
     ReqIn:
         Or:
         - Dashes: one
           Difficulty: hard
         - Dashes: two