ASide:
 - Room: "C-01"
   Holes:
   - Side: Down
     Idx: 0
     Kind: none
   - Side: Down
     Idx: 1
     Kind: none
   - Side: Up
     Idx: 0
     Kind: none
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: inout
   InternalEdges:
     - Split: LeftToRight
       ReqOut:
         Dashes: one
       ReqIn: 
         Dashes: two
 - Room: "C-02"
 # enterable 0 dash without the InternalEdges tag setup, will have to test if it persists when brought back
   Holes:
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Down
     Idx: 0
     Kind: none
   - Side: Down
     Idx: 1
     Kind: none
   - Side: Down
     Idx: 2
     Kind: none
   - Side: Down 
     Idx: 3
     Kind: none
   - Side: Down
     Idx: 4
     Kind: inout
   - Side: Down 
     Idx: 5
     Kind: none
   - Side: Down 
     Idx: 6
     Kind: none
   - Side: Down 
     Idx: 7
     Kind: none
   - Side: Down
     Idx: 8
     Kind: none
   - Side: Right
     Idx: 0
     Kind: inout
     ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
          Key: true
          KeyholeID: 196
        - Dashes: two
          Key: true
          KeyholeID: 196
#   InternalEdges:
#     - To: "left"
#     ReqBoth:
#        Or:
#        - Dashes: one
#          Difficulty: hard
#          Key: true
#          KeyholeID: 196
#        - Dashes: two
#          Key: true
#          KeyholeID: 196
 - Room: "C-03"
   Holes:
   - Side: Up
     Idx: 0 
     Kind: inout
     ReqBoth:
         Or:
         - Dashes: one
           Difficulty: hard
         - Dashes: two
   InternalEdges:
     - Collectable: 0
   ReqOut:
         Or:
         - Dashes: one
           Difficulty: hard
         - Dashes: two
 - Room: "C-04"
   Holes:
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: out
   - Side: Down
     Idx: 0
     Kind: none
   - Side: Down
     Idx: 1
     Kind: none
   - Side: Down
     Idx: 2
     Kind: none
   - Side: Down
     Idx: 3
     Kind: none
   - Side: Down
     Idx: 4
     Kind: none
   - Side: Down
     Idx: 5
     Kind: none
   - Side: Down
     Idx: 6
     Kind: none
   - Side: Down
     Idx: 7
     Kind: none
     ReqBoth:
         Or:
         - Dashes: one
           Difficulty: hard
         - Dashes: two
 - Room: "C-05"
   Holes:
   - Side: Down
     Idx: 3
     Kind: none
   - Side: Down
     Idx: 4
     Kind: none
   - Side: Down
     Idx: 5
     Kind: none
   - Side: Right
     Idx: 0
     Kind: inout
     ReqBoth:
       Or:
       - Dashes: one
       - Dashes: two
   InternalEdges:
   - To: "left"
     ReqBoth:
         Dashes: one
   Subrooms:
   - Room: "left"
   Holes:
   - Side: Down
     Idx: 0
     Kind: none
   - Side: Down
     Idx: 1
     Kind: none
   - Side: Down
     Idx: 2
     Kind: none
   - Side: Left
     Idx: 0
     Kind: unknown
     ReqOut:
       Or:
       - Dashes: one
         Difficulty: expert
       - Dashes: two
         Difficulty: hard
   - Side: Left
     Idx: 1
     Kind: inout
     ReqOut: 
       Dashes: one
   - Side: Up
     Idx: 0
     Kind: unknown
     ReqOut:
       Dashes: two
 - Room: "C-06"
   Holes:
   - Side: Down 
     Idx: 0
     Kind: none
   - Side: Down 
     Idx: 1
     Kind: none
   - Side: Down 
     Idx: 2
     Kind: none
   - Side: Down 
     Idx: 3
     Kind: none
   - Side: Down 
     Idx: 4
     Kind: none
   - Side: Down 
     Idx: 5
     Kind: none
   - Side: Down 
     Idx: 6
     Kind: none
   - Side: Down 
     Idx: 7
     Kind: none
   - Side: Up
     Idx: 0
     Kind: none
   - Side: Up
     Idx: 1
     Kind: none
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: inout
   InternalEdges:
     - Split: LeftToRight
       ReqOut:
         Or:
         - Dashes: one
           Difficulty: hard
         - Dashes: two
       ReqIn:
         Or:
         - Dashes: two
           Difficulty: expert
         - Dashes: one
           Difficulty: perfect
   Tweaks:
   - Name: "spinner"
     ID: 1074
     Update: 
       Remove: true
   - Name: "spinner"
     ID: 1033
     Update: 
       Remove: true
 - Room: "C-Cassette"
   End: true
   Holes:
   - Side: Left
     Idx: 0
     Kind: in
     ReqBoth:
         Or:
         - Dashes: one
           Difficulty: hard
         - Dashes: two