ASide:
  - Room: "D-01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Down
      Idx: 0
      Kind: unknown
    - Side: Down
      Idx: 1
      Kind: unknown
    - Side: Up
      Idx: 0
      Kind: unknown
    - Side: Up
      Idx: 1
      Kind: unknown
    - Side: Up
      Idx: 2
      Kind: unknown
    InternalEdges:
    - To: "right"
      ReqBoth:
        Or:
        - Dashes: two
          Difficulty: normal
        - Dashes: one
          Difficulty: hard
    Subrooms:
    - Room: "right"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      - Side: Up
        Idx: 3
        Kind: unknown
      - Side: Up
        Idx: 4
        Kind: unknown
      - Side: Down
        Idx: 2
        Kind: unknown
      - Side: Down
        Idx: 3
        Kind: unknown
    Tweaks:
    - Name: "spawn"
      Update:
        Add: true
        X: 7104
        Y: -32
  - Room: "D-02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: unknown
    - Side: Left
      Idx: 1
      Kind: unknown
    - Side: Left
      Idx: 2
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Down
      Idx: 0
      Kind: unknown
    - Side: Down
      Idx: 1
      Kind: unknown
    - Side: Down
      Idx: 2
      Kind: unknown
    - Side: Up
      Idx: 0
      Kind: unknown
    - Side: Up
      Idx: 1
      Kind: unknown
    - Side: Up
      Idx: 2
      Kind: unknown
  - Room: "D-03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Left
      Idx: 1
      Kind: in
      ReqIn:
        Dashes: one
        Difficulty: hard
  - Room: "D-04"
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    - Side: Up
      Idx: 1
      Kind: unknown
    - Side: Down
      Idx: 0
      Kind: unknown
    - Side: Down
      Idx: 1
      Kind: unknown
    - Side: Down
      Idx: 2
      Kind: unknown
    - Side: Down
      Idx: 3
      Kind: unknown
    - Side: Down
      Idx: 4
      Kind: unknown
    - Side: Down
      Idx: 5
      Kind: unknown
  - Room: "D-05"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    InternalEdges: 
    - To: "top"
      ReqOut:
          Dashes: one 
          Difficulty: hard
      ReqIn:
          Or:
          - Dashes: one
            Difficulty: expert
          - Dashes: two
            Difficulty: hard
    Subrooms:
    - Room: "top"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
        ReqOut:
          Dashes: one 
          Difficulty: hard
        ReqIn:
          Or:
          - Dashes: one
            Difficulty: expert
          - Dashes: two
            Difficulty: hard
    Tweaks:
    - Name: "jumpThru"
      ID: 1010
      Update:
        X: 48
        Width: 24
    - Name: "jumpThru"
      ID: 1291
      Update:
        X: 264
        Width: 16
  - Room: "D-06"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: two
          Difficulty: hard
        - Dashes: one
          Difficulty: expert
    - Side: Down
      Idx: 0
      Kind: unknown
    - Side: Down
      Idx: 1
      Kind: unknown
    - Side: Down
      Idx: 2
      Kind: unknown
    - Side: Down
      Idx: 3
      Kind: unknown
    - Side: Down
      Idx: 4
      Kind: unknown
    - Side: Down
      Idx: 5
      Kind: unknown
    - Side: Down
      Idx: 6
      Kind: unknown
    - Side: Down
      Idx: 7
      Kind: unknown
    - Side: Down
      Idx: 8
      Kind: unknown
    - Side: Down
      Idx: 9
      Kind: unknown
    - Side: Down
      Idx: 10
      Kind: unknown
    - Side: Down
      Idx: 11
      Kind: unknown
    - Side: Down
      Idx: 12
      Kind: unknown
    - Side: Down
      Idx: 13
      Kind: unknown
    - Side: Down
      Idx: 14
      Kind: unknown
    - Side: Down
      Idx: 15
      Kind: unknown
    - Side: Up
      Idx: 0
      Kind: unknown
    - Side: Up
      Idx: 1
      Kind: unknown
    - Side: Up
      Idx: 2
      Kind: unknown
    - Side: Up
      Idx: 3
      Kind: unknown
    - Side: Up
      Idx: 4
      Kind: unknown
    - Side: Up
      Idx: 5
      Kind: unknown
  - Room: "D-Cassette"
    End: true
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
      ReqIn:
        Dashes: one
        Difficulty: hard
    - Side: Right
      Idx: 0
      Kind: unknown
    - Side: Down
      Idx: 0
      Kind: unknown
    - Side: Down
      Idx: 1
      Kind: unknown
    - Side: Down
      Idx: 2
      Kind: unknown
    - Side: Down
      Idx: 3
      Kind: unknown
    - Side: Down
      Idx: 4
      Kind: unknown
    - Side: Up
      Idx: 0
      Kind: unknown
    - Side: Up
      Idx: 1
      Kind: unknown