ASide: # MANY MANY MANY areas you can open with some tweaks to jumpthrus but idk how worth it is
 - Room: "G-01"
   Holes:
   - Side: Down
     Idx: 0
     Kind: unknown
   - Side: Down
     Idx: 1
     Kind: unknown
   - Side: Left
     Idx: 0
     Kind: none
   - Side: Left
     Idx: 1
     Kind: none
   - Side: Left
     Idx: 2
     Kind: none
   - Side: Left
     Idx: 3
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: none
   - Side: Up
     Idx: 0
     Kind: out
     ReqBoth:
       Dashes: two
       Difficulty: hard
 - Room: "G-02"
   Holes:
   - Side: Down
     Idx: 0
     Kind: in
   - Side: Down
     Idx: 1
     Kind: unknown
   - Side: Down
     Idx: 2
     Kind: unknown
   - Side: Down
     Idx: 3
     Kind: none
   - Side: Down
     Idx: 4
     Kind: none
   - Side: Down
     Idx: 5
     Kind: none
   - Side: Down
     Idx: 6
     Kind: unknown
   - Side: Down
     Idx: 7
     Kind: none
   - Side: Down
     Idx: 8
     Kind: unknown
   - Side: Down
     Idx: 9
     Kind: none
   - Side: Down
     Idx: 10
     Kind: none
   - Side: Up
     Idx: 0
     Kind: unknown
   - Side: Up
     Idx: 1
     Kind: none
   - Side: Up
     Idx: 2
     Kind: out
     ReqOut:
       Dashes: two
       Difficulty: expert
 - Room: "G-03"
   Holes:
   - Side: Left
     Idx: 0
     Kind: unknown
     ReqIn: 
       Dashes: one
       Difficulty: hard
   - Side: Left
     Idx: 1
     Kind: none
   - Side: Left
     Idx: 2
     Kind: none
   - Side: Right
     Idx: 0
     Kind: unknown
     ReqIn:
       Dashes: one
       Difficulty: hard
   - Side: Right
     Idx: 1
     Kind: none
   - Side: Right
     Idx: 2
     Kind: none
   - Side: Down
     Idx: 0
     Kind: in
   - Side: Up
     Idx: 0
     Kind: out
     ReqOut:
         Dashes: two
         Difficulty: expert
   Tweaks: # the single most annoying tweak to code of all time, hands down. definitely very creative though, and all it does is allow entering through 2 holes lol
   - Name: "spikesLeft"
     Update:
       Add: true
       X: 408
       Y: 280
       Height: 80
       Type: outline
   - Name: "spikesUp"
     Update:
       Add: true
       X: 408 
       Y: 280
       Width: 24
       Type: outline
   - Name: "spikesRight"
     Update:
       Add: true
       X: 432
       Y: 280
       Height: 80
       Type: outline
   - Name: "spikesDown"
     Update:
       Add: true
       X: 376
       Y: 224
       Width: 24
       Type: outline
   - Name: "spikesLeft"
     Update:
       Add: true
       X: 376
       Y: 192
       Height: 32
       Type: outline
   - Name: "spikesLeft"
     Update:
       Add: true
       X: 376
       Y: 120
       Height: 32
       Type: outline
   - Name: "spikesRight"
     Update:
       Add: true
       X: 400
       Y: 152
       Height: 40
       Type: outline
   - Name: "spikesUp"
     Update:
       Add: true
       X: 376
       Y: 120
       Width: 24
       Type: outline
   - Name: "spikesDown"
     Update:
       Add: true
       X: 432
       Y: 104
       Width: 24
       Type: outline
   - Name: "spikesUp"
     Update:
       Add: true
       X: 432
       Y: 80
       Width: 24
       Type: outline
   - Name: "dreamBlock"
     Update:
       Add: true
       X: 408
       Y: 280
       Width: 24
       Height: 80
   - Name: "dreamBlock"
     Update:
       Add: true
       X: 376
       Y: 120
       Width: 24
       Height: 104
   - Name: "dreamBlock"
     Update:
       Add: true
       X: 432
       Y: 80
       Width: 24
       Height: 24
 - Room: "G-04"
   Holes:
   - Side: Down
     Idx: 0
     Kind: in
   - Side: Down
     Idx: 1
     Kind: unknown
   - Side: Down
     Idx: 2
     Kind: unknown
   - Side: Down
     Idx: 3
     Kind: unknown
   - Side: Down
     Idx: 4
     Kind: unknown
   - Side: Down
     Idx: 5
     Kind: unknown
   - Side: Down
     Idx: 6
     Kind: unknown
   - Side: Down
     Idx: 7
     Kind: unknown
   - Side: Down
     Idx: 8
     Kind: unknown
   - Side: Down
     Idx: 9
     Kind: unknown
   - Side: Down
     Idx: 10
     Kind: unknown
   - Side: Up
     Idx: 0
     Kind: unknown
   - Side: Up
     Idx: 1
     Kind: unknown
   - Side: Up
     Idx: 2
     Kind: unknown
   - Side: Up
     Idx: 3
     Kind: unknown
   - Side: Up
     Idx: 4
     Kind: unknown
   - Side: Up
     Idx: 5
     Kind: out
     ReqBoth:
          Dashes: two
          Difficulty: expert
 - Room: "G-05"
   Holes:
   - Side: Down
     Idx: 0
     Kind: in
   - Side: Down
     Idx: 1
     Kind: unknown
   - Side: Down
     Idx: 2
     Kind: unknown
   - Side: Down
     Idx: 3
     Kind: unknown
   - Side: Down
     Idx: 4
     Kind: unknown
     ReqIn:
       Dashes: two
   - Side: Down
     Idx: 5
     Kind: unknown
   - Side: Down
     Idx: 6
     Kind: none
   - Side: Down
     Idx: 7
     Kind: unknown
   - Side: Down
     Idx: 8
     Kind: unknown
   - Side: Down
     Idx: 9
     Kind: unknown
   - Side: Down
     Idx: 10
     Kind: unknown
   - Side: Down
     Idx: 11
     Kind: unknown
   - Side: Up
     Idx: 0
     Kind: out
     ReqBoth:
       Dashes: two
       Difficulty: expert
 - Room: "G-06"
   Holes:
   - Side: Left
     Idx: 0
     Kind: unknown
   - Side: Right
     Idx: 0
     Kind: unknown
   - Side: Down
     Idx: 0
     Kind: in
   - Side: Up
     Idx: 0
     Kind: out
     ReqBoth:
       Dashes: two
       Difficulty: hard
 - Room: "G-07a"
   Holes:
   - Side: Down
     Idx: 0
     Kind: in
   - Side: Up
     Idx: 0
     Kind: out
     ReqBoth:
       Dashes: two
       Difficulty: hard
 - Room: "G-07b"
   Holes:
   - Side: Left
     Idx: 0
     Kind: none
   - Side: Down
     Idx: 0
     Kind: in
   - Side: Down
     Idx: 1
     Kind: unknown
   - Side: Down
     Idx: 2
     Kind: unknown
   - Side: Up
     Idx: 0
     Kind: none
   - Side: Up
     Idx: 1
     Kind: unknown
   - Side: Up
     Idx: 2
     Kind: none
   - Side: Up
     Idx: 3
     Kind: out
     ReqBoth:
       Dashes: two
       Difficulty: expert
 - Room: "G-07c"
   Holes:
   - Side: Left
     Idx: 0
     Kind: unknown
   - Side: Down
     Idx: 0
     Kind: in
   - Side: Down
     Idx: 1
     Kind: unknown
   - Side: Down
     Idx: 2
     Kind: unknown
   - Side: Down
     Idx: 3
     Kind: unknown
   - Side: Up
     Idx: 0
     Kind: unknown
   - Side: Up
     Idx: 1
     Kind: unknown
   - Side: Up
     Idx: 2
     Kind: out
     ReqBoth:
       Dashes: two
       Difficulty: expert
 - Room: "G-07d"
   Holes:
   - Side: Up
     Idx: 0
     Kind: unknown
   - Side: Up
     Idx: 1
     Kind: unknown
   - Side: Up
     Idx: 2
     Kind: unknown
   - Side: Up
     Idx: 3
     Kind: unknown
   - Side: Up
     Idx: 4
     Kind: unknown
   - Side: Up
     Idx: 5
     Kind: unknown
   - Side: Up
     Idx: 6
     Kind: out
   - Side: Down
     Idx: 0
     Kind: unknown
   - Side: Down
     Idx: 1
     Kind: unknown
   - Side: Down
     Idx: 2
     Kind: unknown
   - Side: Down
     Idx: 3
     Kind: in
     ReqBoth:
           Dashes: two
           Difficulty: expert
 - Room: "G-07e"
   Holes:
   - Side: Down
     Idx: 0
     Kind: in
   - Side: Left
     Idx: 0
     Kind: unknown
   - Side: Right
     Idx: 0
     Kind: unknown
   - Side: Up
     Idx: 0
     Kind: out
     ReqBoth:
         Dashes: two
 - Room: "G-Cassette"
   End: true
   Holes:
   - Side: Down
     Idx: 0
     Kind: in
   - Side: Up
     Idx: 0
     Kind: unknown
   - Side: Left
     Idx: 0
     Kind: unknown
   - Side: Right
     Idx: 0
     Kind: unknown
     ReqBoth:
           Dashes: two
           Difficulty: hard