ASide: 
 - Room: "H-00" # currently can't be added because of heart barrier
   Holes: 
   - Side: Left
     Idx: 0
     Kind: none
   - Side: Up
     Idx: 0
     Kind: none
   - Side: Down
     Idx: 0
     Kind: none
   - Side: Right
     Idx: 0
     Kind: none
 - Room: "H-01"
   Holes: 
   - Side: Left
     Idx: 0
     Kind: in
   - Side: Down
     Idx: 0
     Kind: unknown
   - Side: Down
     Idx: 1
     Kind: unknown
   - Side: Down
     Idx: 2
     Kind: unknown
   - Side: Down
     Idx: 3
     Kind: unknown
   - Side: Down
     Idx: 4
     Kind: unknown
   - Side: Down
     Idx: 5
     Kind: unknown
   - Side: Up
     Idx: 0
     Kind: unknown
   - Side: Right
     Idx: 0
     Kind: inout
     ReqBoth:
       Dashes: two
       Difficulty: hard
 - Room: "H-02" 
   Holes: 
   - Side: Left
     Idx: 0
     Kind: in
   - Side: Down
     Idx: 0 
     Kind: unknown
   - Side: Down
     Idx: 1
     Kind: unknown
   - Side: Up
     Idx: 0 
     Kind: unknown
   - Side: Up
     Idx: 1
     Kind: out
     ReqBoth:
       Or:
       - Dashes: two
         Difficulty: hard
       - Dashes: one
         Difficulty: expert
       - Dashes: zero
         Difficulty: perfect
 - Room: "H-03"
   Core: 
     Bottom: hot
     Top: cold
   Holes: 
   - Side: Down
     Idx: 0
     Kind: inout
   - Side: Down
     Idx: 1 
     Kind: unknown
   - Side: Down
     Idx: 2
     Kind: unknown
   - Side: Up
     Idx: 0 
     Kind: inout
   - Side: Up
     Idx: 1 
     Kind: unknown
   - Side: Up
     Idx: 2 
     Kind: unknown
     ReqBoth:
       Or:
       - Dashes: one
         Difficulty: perfect
       - Dashes: two
         Difficulty: hard
   Tweaks:
   - Name: "jumpThru"
     ID: 434
     Update:
       Width: 16
 - Room: "H-04"
   Holes: 
   - Side: Down
     Idx: 0
     Kind: in
   - Side: Up
     Idx: 0 
     Kind: out
     ReqBoth:
       Dashes: two
       Difficulty: hard
 - Room: "H-05"
   Holes: 
   - Side: Down
     Idx: 0
     Kind: in
   - Side: Down
     Idx: 1
     Kind: unknown
   - Side: Up
     Idx: 0 
     Kind: unknown
   - Side: Right
     Idx: 0
     Kind: inout
     ReqBoth:
       Dashes: two
       Difficulty: hard
 - Room: "H-06"
   Holes: 
   - Side: Left
     Idx: 0
     Kind: in
   - Side: Down
     Idx: 0 
     Kind: unknown
   - Side: Down
     Idx: 1 
     Kind: unknown
   - Side: Down
     Idx: 2
     Kind: unknown
   - Side: Down
     Idx: 3
     Kind: unknown
     ReqIn:
       Dashes: two
       Difficulty: perfect
   - Side: Down
     Idx: 4 
     Kind: unknown
   - Side: Down
     Idx: 5 
     Kind: unknown
   - Side: Down
     Idx: 6 
     Kind: unknown
   - Side: Down
     Idx: 7 
     Kind: unknown
   - Side: Up
     Idx: 0 
     Kind: none
   - Side: Up
     Idx: 1
     Kind: unknown
   - Side: Up
     Idx: 2 
     Kind: unknown
   - Side: Up
     Idx: 3 
     Kind: unknown
   - Side: Up
     Idx: 4 
     Kind: unknown
   - Side: Up
     Idx: 5 
     Kind: unknown
   - Side: Up
     Idx: 6
     Kind: unknown
   - Side: Right
     Idx: 0 
     Kind: out
     ReqBoth:
       Dashes: two
       Difficulty: expert
 - Room: "H-Cassette"
   End: true
   Holes: 
   - Side: Left
     Idx: 0
     Kind: in
   - Side: Up
     Idx: 0 
     Kind: unknown
   - Side: Down
     Idx: 0 
     Kind: unknown
     ReqEnd:
       Or:
       - Dashes: two
         Difficulty: hard
       - Dashes: one
         Difficulty: perfect