ASide:
 - Room: "J-01"
   Holes:
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: inout
 - Room: "J-02"
   Holes:
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: inout
 - Room: "J-03"
   Holes:
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: inout
   Tweaks:
     - Name: spring
       Update:
         Add: true
         X: 144
         Y: 736
 - Room: "J-04"
   Holes:
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 1
     Kind: none
   - Side: Down
     Idx: 6
     Kind: none
   Tweaks:
   - Name: "booster"
     Update:
       Add: true
       X: 800
       Y: 88
 - Room: "J-05" 
   End: true
   Holes:
   - Side: Left
     Idx: 0
     Kind: inout
   - Side: Right
     Idx: 0
     Kind: inout